### ISSUE TITLE
proxy 1.2 cannot use local files. TypeError: mime.lookup is not a function

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.proxy#14]
If I try to serve files I get always below error: 
`TypeError: mime.lookup is not a function
    at that.app.use (/opt/iobroker/node_modules/iobroker.proxy/lib/proxy.js:229:46)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/opt/iobroker/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:284:7`

This happens with any file, example if you install in proxy a context `test/` and the path is `/opt/iobroker/iobroker-data/files/web` for example.

There is a second error: you get files listed if you use above example. On this level you can click on the files and if they are files 1st error shows up, if they are folders, like admin, like `lib` the folder opens but you cannot click then on any item there because the the server does not add the `lib/` subdir in the file link, so all files just have  `./` in front, even if they are in a sub directory of the proxy folder! 

Sorry, running Node V 10.19 and iobroker.web 3.0.2 but have the same problem on my production system running Proxy 1.1.1 and web 2.4.6

**Comment by GermanBluefox** [comment]
Fixed with 1.2.1
