### ISSUE TITLE
Invalid handling of mimeTypes

### ISSUE THREAD

**Issue by FrankOverIP** [ioBroker/ioBroker.proxy#15]
I have created a proxy mapping to a local folder. Within this folder exists a file i18n.properties. When I try to access this file I get an exception in line 229 of proxy.js. Requests to other files, eg. index.html, work fine.

I could fix the problem with a surrounding try/catch for mime.getType(fileExt);

**Comment by Apollon77** [comment]
Please post the full error message

**Comment by FrankOverIP** [comment]
This is the result of a request to /proxy.0/ui5fs/webapp/i18n/i18n.properties
```
TypeError: Cannot read property 'indexOf' of null
    at ServerResponse.contentType (/opt/iobroker/node_modules/express/lib/response.js:595:17)
    at /opt/iobroker/node_modules/iobroker.proxy/lib/proxy.js:229:29
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/opt/iobroker/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
```

**Comment by Apollon77** [comment]
Hm ... it seems that the mime libray can not determine the mimetype of the file

**Comment by Apollon77** [comment]
Please try Github version - versnumber will stay same, so please restart proxy and web afterwards. does it work?

**Comment by FrankOverIP** [comment]
The changed version works fine. 

However, now I'm running into another problem. A request to http://<host>/proxy.0/ui5fs/webapp/manifest.json?sap-language=DE produces return code 404 - not found. The same request without the parameter works as expected. 
As the file based proxy can hardly work as a real web server, I guess such parameters should simply be ignored. At least in my case this would be better than returning 'not found'.

**Comment by Apollon77** [comment]
Ok, try Github version again. workks that now? (and rest still?) :-)
It now checks for # or ? in patch and cuts at that point.

**Comment by FrankOverIP** [comment]
Yes, now it works. I could launch a simple openui5 application with the files being provided by proxy adapter.

**Comment by Apollon77** [comment]
1.2.2 released
